<!--
/**
*  Module: jQuery AJAX-ZOOM for Magento, /app/design/adminhtml/default/default/template/axzoom/tab360-sets.phtml
*  Copyright: Copyright (c) 2010-2015 Vadim Jacobi
*  License Agreement: http://www.ajax-zoom.com/index.php?cid=download
*  Version: 1.0.0
*  Date: 2015-09-08
*  Review: 2015-09-08
*  URL: http://www.ajax-zoom.com
*  Documentation: http://www.ajax-zoom.com/index.php?cid=modules&module=magento
*
*  @author    AJAX-ZOOM <support@ajax-zoom.com>
*  @copyright 2010-2015 AJAX-ZOOM, Vadim Jacobi
*  @license   http://www.ajax-zoom.com/index.php?cid=download
*/
-->

<?php
$model = Mage::getModel('axzoom/ax360');
$setsGroups = $model->getCollection()->addFieldToFilter('id_product', $productId)->getData();

$model = Mage::getModel('axzoom/ax360set');
$sets = $model->getSets($productId);
?>
<style type="text/css">
	.hide {
		display: none !important;
	}
	#imageTableSetsRows .active td {
		background-color: #FFFFE0 !important;
	}
</style>



<div id="product-images360sets" class="entry-edit">
	<div class="entry-edit-head">
		<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('360/3D Views') ?></h4>
	</div>
	<div class="fieldset fieldset-wide" id="group_fields9">
		<div class="hor-scroll">
			<div>
				<a class="link_add" href="#"> <i class="icon-plus"></i> <?php echo $this->__('Add a new 360/3D view') ?></a>
			</div>
			<br>

			<div class="row" id="newForm" style="display:none">
				<table cellspacing="0" class="form-list">
					<tbody>
						<tr>
							<td class="label"><label for="set_name"><?php echo $this->__('Create a new') ?></label></td>
							<td class="value">
								<input type="text" id="set_name" name="set_name" value="" />
								<p class="note"><?php echo $this->__('Please enter any name') ?></p>
							</td>
							<td class="scope-label"><span class="nobr"></span></td>
						</tr>
						<?php if ($setsGroups): ?>
						<tr>
							<td colspan="3"><b><?php echo $this->__('OR') ?></b></td>
						</tr>
						<tr>
							<td class="label"><label for="existing"><?php echo $this->__('Add to existing 3D as next row') ?></label></td>
							<td class="value">
								<select name="existing" id="existing">
									<option value="" style="min-width: 100px"><?php echo $this->__('Select') ?></option>
									<?php foreach ($setsGroups as $group): ?>
									<option value="<?php echo $group['id_360'] ?>"><?php echo $group['name'] ?></option>
									<?php endforeach ?>
								</select>
								<p class="note"><?php echo $this->__('You should not select anything here unless you want to create 3D (not 360) which contains more than one row!') ?></p>
							</td>
							<td class="scope-label"><span class="nobr"></span></td>
						</tr>
						<?php endif; ?>
						
						<tr>
							<td class="label"><label for="zip"><?php echo $this->__('Add images from ZIP archive') ?></label></td>
							<td class="value">
								<input type="checkbox" id="zip" name="zip" value="1" />
								<p class="note"><?php echo $this->__('This is the most easy and quick way of adding 360 views to your product! Upload over FTP your 360\'s zipped (each images set in one zip file) to /modules/ajaxzoom/zip/ directory. After you did so these zip files will instantly appear in the select field below. All you have to do then is select one of the zip files and press \'add\' button. Images from the selected zip file will be instantly imported.') ?></p>
							</td>
							<td class="scope-label"><span class="nobr"></span></td>
						</tr>
						<tr class="field-arcfile" style="display:none;">
							<td class="label"><label for="arcfile"><?php echo $this->__('Select ZIP archive') ?></label></td>
							<td class="value">
								<?php if ($files): ?>
								<select name="arcfile" id="arcfile">
									<option value=""><?php echo $this->__('Select') ?></option>
									<? foreach ($files as $file): ?>
									<option value="<?php echo $file ?>"><?php echo $file ?></option>
									<? endforeach; ?>
								</select>
								<?php else: ?>
								<p><b><?php echo $this->__('There are no files found in the "js/axzoom/zip" folder') ?></b></p>
								<?php endif; ?>
							</td>
							<td class="scope-label"><span class="nobr"></span></td>
						</tr>
						
						<tr>
							<td></td>
							<td>
								<button type="button" class="scalable save save_set" >
									<span><span><span><?php echo $this->__('Add') ?></span></span></span>
								</button>
							</td>
							<td></td>
						</tr>
					</tbody>
				</table>
			</div>
			<br>
			<div class="row">
				<div class="grid">
					<table class="data border" id="imageTableSets" >
						<thead>
							<tr class="headings">
								<th><?php echo $this->__('Cover Image') ?></th>
								<th><?php echo $this->__('Name') ?></th>
								<th><?php echo $this->__('Active') ?></th>
								<th class="last" style="width:240px;"><?php echo $this->__('Actions') ?></th>
							</tr>
						</thead>
						<tbody id="imageTableSetsRows">
						</tbody>
					</table>
				</div>

				<table id="lineSet" style="display:none;">
					<tr id="set_id" data-group="group_id">
						<td><img src="../modules/ajaxzoom/views/img/image_path.gif" alt="legend" title="legend" class="img-thumbnail" /></td>
						<td>legend</td>
						<td>
							<span class="switch prestashop-switch fixed-width-lg hide_class switch-status">
								<input type="radio" name="status_field" id="status_field_on" value="1" checked_on />
								<label class="t" for="status_field_on"><?php echo $this->__('Yes') ?></label>
								<input type="radio" name="status_field" id="status_field_off" value="0" checked_off />
								<label class="t" for="status_field_off"><?php echo $this->__('No') ?></label>
								<a class="slide-button btn"></a>
							</span>
						</td>
						<td>
							<button class="delete_set scalable delete" ><?php echo $this->__('Delete') ?></button>
							<button class="images_set scalable" ><?php echo $this->__('Images') ?></button>
							<button class="scalable preview_set hide_class" ><?php echo $this->__('Preview') ?></button>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>


<script>
	var id_product = '<?php echo $productId ?>';

	jQuery(document).ready(function($){
		
		function setLine(id, path, position, legend, status, group_id)
		{
			line = $("#lineSet").html();
			line = line.replace(/set_id/g, id);
			line = line.replace(/group_id/g, group_id);
			line = line.replace(/legend/g, legend);
			line = line.replace(/status_field/g, 'status_' + id);
			line = line.replace(/\.\.\/modules\/ajaxzoom\/views\/img\/image_path\.gif/g, path);
			line = line.replace(/<tbody>/gi, "");
			line = line.replace(/<\/tbody>/gi, "");

			if(status == '1') {
				line = line.replace(/checked_on/g, 'checked');
				line = line.replace(/checked_off/g, '');
			} else {
				line = line.replace(/checked_on/g, '');
				line = line.replace(/checked_off/g, 'checked');
			}

			if($('tr[data-group=' + group_id + ']').length) {
				line = line.replace(/hide_class/g, 'hide');
			}

			$("#imageTableSetsRows").append(line);
		}

		function afterUpdateStatus(data) {
			data = $.parseJSON(data);
			showSuccessMessage(data.confirmations);
		}

		function afterDeleteSet(data) {
			var data = $.parseJSON(data);
			$('tr#' + data.id_360set).remove();
			showSuccessMessage(data.confirmations);

			// remove set option from the dropdowns
			if(data.removed == '1') {
				$("select#id_360 option[value='" + data.id_360 + "']").remove();
				$("select#existing option[value='" + data.id_360 + "']").remove();
			}
		}

		function afterAddSet(data) {
			var data = $.parseJSON(data);

			if(data.sets.length > 0) {
				for (var i = 0; i < data.sets.length; i++) {
					var set = data.sets[i];
					setLine(set.id_360set, set.path, "", set.name, set.status, set.id_360);
				};
			} else {
				setLine(data.id_360set, data.path, "", data.name, data.status, data.id_360);
			}

			$('.link_add').find('i').removeClass('icon-minus').addClass('icon-plus');
			$('#newForm').hide();
			$('#set_name').val('');
			$('#existing').val('');

			if(data.new_id != '') {
				$('select#id_360')
					.append($("<option></option>")
					.attr("value", data.new_id)
					.attr('data-settings', data.new_settings)
					.attr('data-combinations', '[]')
					.text(data.new_name)); 
				$('select#existing').append($("<option></option>").attr("value", data.new_id).text(data.new_name)); 
			}
			showSuccessMessage(data.confirmations);
		}

		function afterGetImages(data) {
			var data = $.parseJSON(data);
			
			for (var i = 0; i < data.images.length; i++) {
				imageLine360(data.images[i]['id'], data.images[i]['thumb'], '', "", "", "");
			};
			
		}


		$('#zip').change(function () {
			if($(this).is(':checked')) {
				$('.field-arcfile').show();
			} else {
				$('.field-arcfile').hide();
			}
		});

		$('.link_add').click(function (e) {
			e.preventDefault();

			var icon = $(this).find('i');

			if(icon.hasClass('icon-plus')) {
				icon.removeClass('icon-plus').addClass('icon-minus');
				$('#newForm').show();
			} else {
				icon.removeClass('icon-minus').addClass('icon-plus');
				$('#newForm').hide();
			}
		});

		$('.switch-status input').die().live('change', function(e) {
			e.preventDefault();
			var status = $(this).val();
			var group_id = $(this).parent().parent().parent().data('group');

			doAdminAjax360('<?php echo Mage::helper("adminhtml")->getUrl("axzoom/index/set360Status") ?>', {
					"id_product" : <?php echo $productId ?>,
					"id_360" : group_id,
					"status" : status}, afterUpdateStatus
			);
			
		});

		$('.preview_set').die().live('click', function(e) {
			e.preventDefault();

			var id360 = $(this).parent().parent().data('group');
			var id360set = $(this).parent().parent().attr('id');

			$.openAjaxZoomInFancyBox({href: '<?php echo Mage::getBaseUrl('js') ?>axzoom/preview/preview.php?3dDir=<?php echo Mage::getModel('axzoom/ax360')->rootFolder() ?>js/axzoom/pic/360/' + id_product + '/' + id360+'&group='+id360+'&id='+id360set, iframe: true});
		});

		$('.images_set').die().live('click', function(e) {
			e.preventDefault();
			
			$('#imageTableSetsRows').find('tr').removeClass('active');
			$(this).parent().parent().addClass('active');
			$('#imageList360').html('');
			$('#file360-success').parent().hide();

			var id = $(this).parent().parent().attr('id');

			doAdminAjax360('<?php echo Mage::helper("adminhtml")->getUrl("axzoom/index/getImages") ?>', {
					"id_product" : <?php echo $productId ?>,
					"id_360set" : id}, afterGetImages
			);
			
			$('#id_360set').val(id);
			$('#product-images360').show();
		});


		$('.save_set').click(function (e) {
			e.preventDefault();	
			
			doAdminAjax360('<?php echo Mage::helper("adminhtml")->getUrl("axzoom/index/addSet") ?>', {
					"name":$('#set_name').val(),
					"existing":$('#existing').val(),
					"zip":$('#zip').is(':checked'),
					"arcfile":$('#arcfile').val(),
					"id_product" : <?php echo $productId ?>}, afterAddSet
			);
		});


		$('.delete_set').die().live('click', function(e)
		{
			e.preventDefault();

			$('#product-images360').hide();
			$('#imageList360').html('');

			var id = $(this).parent().parent().attr('id');
			if (confirm("<?php echo $this->__('Are you sure?') ?>"))
			doAdminAjax360('<?php echo Mage::helper("adminhtml")->getUrl("axzoom/index/deleteSet") ?>', {
					"id_360set":id,
					"id_product" : <?php echo $productId ?>}, afterDeleteSet
			);
		});

		<?php foreach ($sets as $set): ?>
			setLine("<?php echo $set['id_360set'] ?>", "<?php echo $set['path'] ?>", "", "<?php echo $set['name'] ?>", "<?php echo $set['status'] ?>", "<?php echo $set['id_360'] ?>");
		<?php endforeach; ?>
	});
</script>